# kind（Kubernetes IN Docker）でクラスタを作成するための設定です。
# このファイルは、ローカル環境でIngress（外部からのHTTP/HTTPSリクエストをクラスタ内にルーティングする仕組み）
# を動作させるための独自設定を含んでいます。
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  # control-plane（クラスタ全体を管理するマスターノード）に対する設定
  - role: control-plane
    
    # kubeadm（クラスタ構築ツール）の初期設定を上書き（パッチ）します
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            # 該当ノードに "ingress-ready=true" という目印（ラベル）を付けます。
            # 今回デプロイ予定の Ingress NGINX コントローラーは、このラベルがあるノード上でのみ動くように制御されます。
            node-labels: "ingress-ready=true"
    
    # ローカルPC（ホスト）のネットワークポートと、kindが作成したDockerコンテナのポートを繋ぐ設定です
    # これにより、PCのブラウザから localhost:80 や localhost:443 でクラスタ内のアプリにアクセスできるようになります
    extraPortMappings:
      # HTTP（80番ポート）のルーティング設定
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      # HTTPS（443番ポート）のルーティング設定
      - containerPort: 443
        hostPort: 443
        protocol: TCP
